/*
DISCLAIMER: This source code was generated by Dapp, and is supplied to you by
kerofrog.

kerofrog grants you a personal, non-exclusive license to use, reproduce, modify
and redistribute this source code, with or without modifications in source
and/or binary forms.  However, if you redistribute the source code in its entirety
and without modifications, you must retain this notice and the following text and
disclaimers in all such redistributions.

The source code is provided by kerofrog on an "AS IS" basis.  kerofrog makes no
warranties, express or implied, including without limitation the implied warranties
of non-infringement, merchantability and fitness for a particular purpose, regarding
the source code or its use and operation alone or in combination with your products.

In no event shall kerofrog be liable for any special, indirect, incidental or
consequential damages (including, but not limited to, loss of use, data, or profits;
or business interruption) arising in any way out of the use, reproduction,
modification and/or distribution of the source code.

Copyright (C) 2010 kerofrog. All Rights Reserved.
*/

//  PushNonAnimatedSegue.m

#import "PushNonAnimatedSegue.h"

@implementation PushNonAnimatedSegue

- (void) perform {
	UIViewController *des = (UIViewController *) self.destinationViewController;
	UIViewController *src = (UIViewController *) self.sourceViewController;
	[src.navigationController pushViewController:des animated:NO];
}

@end